### ISSUE TITLE
Husarent section missing in Arduino

### ISSUE THREAD

**Issue by jimthedj65** [DominikN/ESP32_cli_eeprom#1]
Hi Dominik,

I have followed your instructions, I am running the latest arduino, I seem to get stuck at step 2 select ESP32 Dev Module under "ESP32 Arduino (Husarnet)" section

When looking under boards I don't see a Husarnet section?

Any assistance greatly appreciated.

**Comment by DominikN** [comment]
Hi, fixed! Just migrated the project to PlatformIO, so providing a right configuration is done automatically.

Also a GitHub Action workflow is configured to make sure the current commit is building fine.
